matrix:
    include:
        - language: cpp
          sudo: false
          compiler: clang
          script:
              - mkdir build && cd build
              - cmake ../
              - cmake --build .
              - ctest --verbose .
        - language: python
          python:
              - "3.6"
              - "3.7"
              - "3.8"
          sudo: false
          install:
              - pip install -r requirements.txt
              - pip install -vvv .
          script:
              - pytest -v test_lin.py
